DELETE FROM ACCOUNTS;
DELETE FROM USERS;
INSERT INTO USERS(ID, USER_NAME) VALUES('1', 'user');
INSERT INTO ACCOUNTS VALUES('123456', 'SGDEBITAC', 'SAVINGS', parsedatetime('04-07-2021', 'dd-MM-yyyy'), 'SGD', 4234.50, '1');